version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-local
    # command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "5173:5173"
    volumes:
      - .:/code
    restart: no